# Generated by Django 2.2 on 2021-10-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('corpo', models.TextField(verbose_name='Comentario')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data da criacao')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'Comentario',
            },
        ),
    ]
